export const menuTree = [
  {
    'id': '2',
    'parentId': '-1',
    'weight': 990,
    'name': '客户管理',
    'path': '/custom',
    'keepAlive': '0',
    'sortOrder': 990,
    'icon': 'icon-rizhiguanli',
    'permission': null,
    'label': '客户管理',
    'type': '0',
    'children': [
      {
        'id': '1592049597122973698',
        'parentId': '2',
        'weight': 999,
        'name': '客户列表',
        'path': '/custom/customer/index',
        'keepAlive': '0',
        'sortOrder': 999,
        'icon': 'icon-daohanglanmoshi02',
        'permission': null,
        'label': '客户列表',
        'type': '0',
      },
      {
        'id': '1592452565295009793',
        'parentId': '2',
        'weight': 999,
        'name': '客户详情',
        'path': '/custom/detail/index',
        'keepAlive': '0',
        'sortOrder': 999,
        'icon': 'icon-pintu',
        'permission': null,
        'label': '客户详情',
        'type': '0',
      },
      {
        'id': '1592452565295009795',
        'parentId': '2',
        'weight': 999,
        'name': '资料审核',
        'path': '/custom/review/index',
        'keepAlive': '0',
        'sortOrder': 999,
        'icon': 'icon-pintu',
        'permission': null,
        'label': '资料审核',
        'type': '0',
      },
      {
        'id': '1592452565295009796',
        'parentId': '2',
        'weight': 999,
        'name': '审核详情',
        'path': '/custom/reviewdetail/index',
        'keepAlive': '0',
        'sortOrder': 999,
        'icon': 'icon-pintu',
        'permission': null,
        'label': '审核详情',
        'type': '0',
      },
    ],
  },
  {
    'id': '3',
    'parentId': '-1',
    'weight': 990,
    'name': '融资审批',
    'path': '/approval',
    'keepAlive': '0',
    'sortOrder': 990,
    'icon': 'icon-rizhiguanli',
    'permission': null,
    'label': '融资审批',
    'type': '0',
    'children': [
      {
        'id': '1592452565295009891',
        'parentId': '3',
        'weight': 999,
        'name': '审批列表',
        'path': '/approval/approvalist/index',
        'keepAlive': '0',
        'sortOrder': 999,
        'icon': 'icon-pintu',
        'permission': null,
        'label': '审批列表',
        'type': '0',
      },
      {
        'id': '1592452565295009893',
        'parentId': '3',
        'weight': 999,
        'name': '审批详情',
        'path': '/approval/approvaldetail/index',
        'keepAlive': '0',
        'sortOrder': 999,
        'icon': 'icon-daohanglanmoshi02',
        'permission': null,
        'label': '审批详情',
        'type': '0',
      },
    ],
  },
  {
    'id': '4',
    'parentId': '-1',
    'weight': 990,
    'name': '报价管理',
    'path': '/quotation',
    'keepAlive': '0',
    'sortOrder': 990,
    'icon': 'icon-rizhiguanli',
    'permission': null,
    'label': '报价管理',
    'type': '0',
    'children': [
      {
        'id': '1592452565295009991',
        'parentId': '3',
        'weight': 999,
        'name': '报价设置',
        'path': '/quotation/quote/index',
        'keepAlive': '0',
        'sortOrder': 999,
        'icon': 'icon-pintu',
        'permission': null,
        'label': '报价设置',
        'type': '0',
      },
    ],
  },
  {
    'id': '1592047782675451906',
    'parentId': '-1',
    'weight': 990,
    'name': '信息安全',
    'path': '/safe',
    'keepAlive': '0',
    'sortOrder': 990,
    'icon': 'icon-rizhiguanli',
    'permission': null,
    'label': '信息安全',
    'type': '0',
    'children': [
      {
        'id': '1',
        'parentId': '1592047782675451906',
        'weight': 999,
        'name': '短信通知',
        'path': '/safe/message/index',
        'keepAlive': '0',
        'sortOrder': 999,
        'icon': 'icon-wangzhan',
        'permission': null,
        'label': '短信通知',
        'type': '0',
      },
      {
        'id': '1592069968983330817',
        'parentId': '1592047782675451906',
        'weight': 999,
        'name': '账号安全',
        'path': '/safe/account/index',
        'keepAlive': '0',
        'sortOrder': 999,
        'icon': 'icon-wangzhan',
        'permission': null,
        'label': '账号安全',
        'type': '0',
      },
    ],
  },
]
